routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Foundation\Auth\EmailVerificationRequest;
use Illuminate\Http\Request;
use App\Contact;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Login & Register Routes.
Auth::routes();

Route::post('/user-register', 'Auth\RegisterController@register')->name('user-register');
Route::post('/login-verify', 'Auth\LoginController@index')->name('user-login');
Route::get('/user/verify/{token}', 'Auth\RegisterController@verifyUser')->middleware('back');
Route::get('/',function(){
    return view('welcome');
});
Route::get('/contact-card/{id}/{shareid}','Contact\ContactController@viewCard')->name('card');



//protected routes

Route::group(['middleware'=>['web','access','status','back']],function(){
Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
Route::resource('/contact','Contact\ContactController');
Route::get('/import-csv','CSV\CSVController@import')->name('import');
Route::post('/upload-csv','CSV\CSVController@uploadCSV')->name('upload');
Route::any ( 'contact/search','Contact\ContactController@searchContact');
Route::get('/logout','Auth\Logincontroller@logout')->name('logout');
Route::get('share','Contact\ContactController@shareLink')->name('linkshare');
});

Route::group(['middleware'=>['web','access','status']],function(){
    Route::get('/export-csv','CSV\CSVController@export')->name('export');
});

app/Contact.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    //
     /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name','last_name', 'contact_email','contact_phone_number', 'contact_address','contact_nickname','contact_company','userId'
    ];

    protected $gaurded = [
        'contactId'
    ];

    protected $primaryKey ='contactId';
}

app/Http/Controllers/Contact/ContactController.php
<?php

namespace App\Http\Controllers\Contact;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\ContactRequest;
use App\Contact;
use App\Share;
use DB;
use Session;
use DataTables;
use Illuminate\Support\Facades\URL;

class ContactController extends Controller
{

    
    /**
     * Show the form for displaying resources.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //
       $data=Contact::where('userId',Session::get('userid'))->paginate(10);
        return view('contact.contact-list',compact('data'));
      
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('contact.add-contact');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ContactRequest $request)
    {
        //
        DB::beginTransaction();
        try{
            $find_contact=Contact::where(['userId'=>Session::get('userid'),'contact_phone_number'=>$request['phone']])->first();
            if($find_contact)
            {
                return redirect()->route('contact.index')->with('warning','Contact already exist with this number') ;   
            }
            $contact= Contact::create([
                'userId'=>Session::get('userid'),
                'first_name' => $request['first_name'],
                'last_name' => $request['last_name'],
                'contact_email' => $request['email'],
                'contact_phone_number' => $request['phone'],
                'contact_address' => $request['address'],
                'contact_nickname' => $request['nickname'],
                'contact_company' => $request['company'],
            ]);
             DB::commit(); 
             return redirect()->route('contact.index')->with('success','Contact has been addded successfully') ;       
            }
        catch(\Exception $e) {   
        DB::rollback();
        throw $e;
        }  
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $id=base64_decode($id);
        $find_contact=Contact::where('contactId',$id)->first();
        if($find_contact){
//custom code
            $share=Share::create([
                'cardId'=>$id,
                'token'=>sha1(time()),
                'expireTime'=>time()+3600
            ]);
         
            return route('card',[base64_encode($id),base64_encode($share->id)]).'?token='.$share->token;
//using laravel inbuilt feature
        // return URL::temporarySignedRoute(
        //     'card', now()->addMinutes(60), ['id' => base64_encode($id)]
        // );
        }
        return redirect()->route('contact.index')->with('warning','No record is found');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $id=base64_decode($id);
        $find_contact=Contact::where('contactId',$id)->first();
        if($find_contact){
            return view('contact.edit-contact',compact('find_contact'));
        }
        return redirect()->route('contact.index')->with('warning','No record is found');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ContactRequest $request, $id)
    {
        //
        $updateData=$request->all();
        $id=base64_decode($id);
        DB::beginTransaction();
        try{
            if(isset($updateData['isUpdate']))
            {
                if($updateData['oldphone']!=$updateData['phone'])
                {
                    $find_contact=Contact::where(['userId'=>Session::get('userid'),'contact_phone_number'=>$updateData['phone']])->first();
                    return redirect()->back()->with('warning','Contact already exist with this number') ; 
                }
                $data=[
                'first_name' => $updateData['first_name'],
                'last_name' => $updateData['last_name'],
                'contact_email' => $updateData['email'],
                'contact_phone_number' => $updateData['phone'],
                'contact_address' => $updateData['address'],
                'contact_nickname' => $updateData['nickname'],
                'contact_company' => $updateData['company'],
                'status'=>$updateData['status']

                ];
                Contact::where('contactId',$id)->update($data);

                DB::commit(); 
                return redirect()->route('contact.index')->with('success','Contact has been updated successfully') ;       
            }
            return redirect()->route('contact.index')->with('success','Invalid request') ; 
           }  
           catch(\Exception $e) {   
            DB::rollback();
            throw $e;
            }
        
    }


    //view card
    public function viewCard(Request $request,$id,$shareid)
    {
        $id=base64_decode($id);
        $shareid=base64_decode($shareid);
        $token=$request->query('token');
        
        $find_entry=Share::where(['shareId'=>$shareid,'token'=>$token])->first();
            // if (! $request->hasValidSignature()) {
            //     abort(401);
            // }
            if(!$find_entry)
            {
                 abort(401);
               
            }
            elseif($find_entry->expireTime<=time()){
                 abort(401);
                
            }
            else{
                $contact=Contact::where('contactId',$id)->first();
                return view('contact.view-contact',compact('contact'));
               
            }
    }

    //search contact
    public function searchContact(Request $request){
        $q = $request->input('q');
        $data=array();
        if($q != ""){
        $data = Contact::where ( 'first_name', 'LIKE', '%' . $q . '%' )
                ->orWhere ( 'last_name', 'LIKE', '%' . $q . '%' )
                ->orWhere ( 'contact_email', 'LIKE', '%' . $q . '%' )
                ->orWhere ( 'contact_phone_number', 'LIKE', '%' . $q . '%' )
                ->paginate (10)->setPath ( '' );
        $pagination = $data->appends ( array (
           'q' => $request->input('q') 
         ) );
        if (count ( $data ) > 0)
         return view ( 'contact.contact-list',compact('data'))->withQuery ( $q );
        }
         return view ( 'contact.contact-list',compact('data'))->with("noresult",'No Details found. Try to search again !' );
       } 
    
   
}

resources/views/contact/add-contact.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Add Contact') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('contact.store') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('First Name') }}</label>

                            <div class="col-md-6">
                                <input id="first_name" type="text" class="form-control @error('first_name') is-invalid @enderror" name="first_name" value="{{ old('first_name') }}"  autocomplete="first_name" autofocus>

                                @error('first_name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Last Name') }}</label>

                            <div class="col-md-6">
                                <input id="last_name" type="text" class="form-control @error('last_name') is-invalid @enderror" name="last_name" value="{{ old('last_name') }}"  autocomplete="last_name" autofocus>

                                @error('last_name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}"  autocomplete="email">

                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="phone" class="col-md-4 col-form-label text-md-right">{{ __('Phone no.') }}</label>

                            <div class="col-md-6">
                                <input id="phone" type="text" class="form-control @error('phone') is-invalid @enderror" name="phone" value="{{ old('phone') }}" maxlength="10"  autocomplete="phone">
                                @error('phone')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="address" class="col-md-4 col-form-label text-md-right">{{ __('Address') }}</label>

                            <div class="col-md-6">
                                <input id="address" type="text" class="form-control @error('address') is-invalid @enderror" name="address" value="{{ old('address') }}"  autocomplete="new-password">

                                @error('address')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="nick" class="col-md-4 col-form-label text-md-right">{{ __('Nickname') }}</label>

                            <div class="col-md-6">
                                <input id="nickname" type="text" class="form-control @error('nickname') is-invalid @enderror" name="nickname" value="{{ old('nickname') }}"  autocomplete="new-password">

                                @error('nickname')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="company" class="col-md-4 col-form-label text-md-right">{{ __('Company') }}</label>

                            <div class="col-md-6">
                                <input id="company" type="text" class="form-control @error('company') is-invalid @enderror" name="company" value="{{ old('company') }}"  autocomplete="new-password">

                                @error('company')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Add') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/contact/contact-list.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Contact List') }}</div>

                <div class="card-body">
                @if (session('success'))
                        <div class="alert alert-success" role="alert">
                            {{ session('success') }}
                        </div>
                        @elseif (session('warning'))
                        <div class="alert alert-danger" role="alert">
                            {{ session('warning') }}
                        </div>
                    @endif
                <div class="container">
                <a href="{{route('contact.create')}}">Add Contact</a><br><br>
                    <form action="{{route('contact.index')}}/search" method="POST" role="search" >
                    @csrf
                        <div class="input-group">
                            <input type="text" class="form-control" name="q"
                                placeholder="Search contact"> <span class="input-group-btn">
                                <button type="submit" class="btn btn-default">
                                    <span class="glyphicon glyphicon-search"></span>
                                </button>
                            </span>
                        </div>
                    </form>
            </div>
                <table class="table mt-4" id="noticeTable">
                <thead>
                    <th> # </th>
                    <th> Person Name </th>
                    <th> Phone No </th>
                    <th> Email </th>
                    <th> Address </th>
                    <th> Status </th>
                    <th> Action </th>
                </thead>
                <tbody>
                @php $n=0; @endphp
                @if(count($data)>0)
                @foreach($data as $contact)
                <tr>
                <td>{{++$n}}</td>
                <td>{{$contact->first_name.' '.$contact->last_name}}</td>
                <td>{{$contact->contact_phone_number}}</td>
                <td>{{$contact->contact_email}}</td>
                <td>{{$contact->contact_address}}</td>
                <td>{{$contact->status==1?'Active':'Inactive'}}</td>
                <td><a href="{{route('contact.edit',base64_encode($contact->contactId))}}"><i class="fa fa-edit"></i></a>
                <a href="{{route('contact.show',base64_encode($contact->contactId))}}" target="_blank"><i class="fa fa-share"></i></a></td>
                <tr>
                @endforeach
                @else
                <td>{{Session::get('noresult')}}</td>

                @endif
                </tbody>
            </table>
            @if(count($data)>0)
            {{ $data->withQueryString()->links() }}
            @endif
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/contact/csv-import.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('CSV Import') }}</div>
                <a href="{{asset('contactimport.csv')}}" class="d-flex-xs middle-xs btn-action font__weight--simibold" download>
                     Download CSV Format
                </a>
                <a href="{{route('export')}}" class="d-flex-xs middle-xs btn-action font__weight--simibold" download>
                     Export CSV
                </a>
                <div class="card-body">
                @if (session('success'))
                        <div class="alert alert-success" role="alert">
                            {{ session('success') }}
                        </div>
                        @elseif (session('warning'))
                        <div class="alert alert-danger" role="alert">
                            {{ session('warning') }}
                        </div>
                    @endif
                    <form method="POST" action="{{ route('upload') }}" enctype='multipart/form-data'>
                        @csrf

                        <div class="form-group row">
                            <label for="csvfile" class="col-md-4 col-form-label text-md-right">{{ __('Choose a csv file') }}</label>

                            <div class="col-md-6">
                                <input id="csvfile" type="file" class="form-control @error('csvfile') is-invalid @enderror" name="csvfile"  autofocus>

                                @error('csvfile')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                       

                       

                        <div class="form-group row mb-0">
                            <div class="col-md-8 offset-md-4">
                                <button type="submit" class="btn btn-primary" name="isCSV" value="yes">
                                    {{ __('Import') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/contact/edit-contact.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Edit Contact') }}</div>

                <div class="card-body">
                @if (session('success'))
                        <div class="alert alert-success" role="alert">
                            {{ session('success') }}
                        </div>
                        @elseif (session('warning'))
                        <div class="alert alert-danger" role="alert">
                            {{ session('warning') }}
                        </div>
                    @endif
                    <form method="POST" action="{{ route('contact.update',base64_encode($find_contact->contactId)) }}">
                        @csrf
                        @METHOD('PUT')

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('First Name') }}</label>

                            <div class="col-md-6">
                                <input id="first_name" type="text" class="form-control @error('first_name') is-invalid @enderror" name="first_name" value="{{ $find_contact->first_name }}"  autocomplete="first_name" autofocus>

                                @error('first_name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Last Name') }}</label>

                            <div class="col-md-6">
                                <input id="last_name" type="text" class="form-control @error('last_name') is-invalid @enderror" name="last_name" value="{{ $find_contact->last_name }}"  autocomplete="last_name" autofocus>

                                @error('last_name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ $find_contact->contact_email }}"  autocomplete="email">

                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="phone" class="col-md-4 col-form-label text-md-right">{{ __('Phone no.') }}</label>

                            <div class="col-md-6">
                                <input id="phone" type="text" class="form-control @error('phone') is-invalid @enderror" name="phone" value="{{ $find_contact->contact_phone_number }}" maxlength="10"  autocomplete="phone">
                                <input type="hidden" name="oldphone" value="{{$find_contact->contact_phone_number}}">
                                @error('phone')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="address" class="col-md-4 col-form-label text-md-right">{{ __('Address') }}</label>

                            <div class="col-md-6">
                                <input id="address" type="text" class="form-control @error('address') is-invalid @enderror" name="address" value="{{ $find_contact->contact_address }}"  autocomplete="new-password">

                                @error('address')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="nick" class="col-md-4 col-form-label text-md-right">{{ __('Nickname') }}</label>

                            <div class="col-md-6">
                                <input id="nickname" type="text" class="form-control @error('nickname') is-invalid @enderror" name="nickname" value="{{ $find_contact->contact_nickname }}"  autocomplete="new-password">

                                @error('nickname')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="company" class="col-md-4 col-form-label text-md-right">{{ __('Company') }}</label>

                            <div class="col-md-6">
                                <input id="company" type="text" class="form-control @error('company') is-invalid @enderror" name="company" value="{{ $find_contact->contact_company }}"  autocomplete="new-password">

                                @error('company')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="status" class="col-md-4 col-form-label text-md-right">{{ __('Status') }}</label>

                            <div class="col-md-6">
                            <select name="status" id="status" class="form-control @error('status') is-invalid @enderror">
                            <option value="1" {{($find_contact->status==1?'selected':'')}}>Active</option>
                            <option value="0" {{($find_contact->status==0?'selected':'')}}>Inactive</option>

                            </select>
                                @error('status')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary" name="isUpdate" value="yes">
                                    {{ __('Update') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/contact/view-contact.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Contact Card') }}</div>
                <div class="card-body">
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">{{$contact->first_name.' '.$contact->last_name}}</h5>
                        <h6 class="card-subtitle mb-2 text-muted">{{$contact->contact_phone_number}}</h6>
                        <p class="card-text">{{$contact->contact_address}}</p>
                        <a  class="card-link">{{$contact->contact_email}}</a>
                        <a  class="card-link">{{$contact->contact_company}}</a>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection